import numpy as np

PARTIALLY_OPEN_THRES = 0.05
FULLY_OPEN_THRES = 0.5
MOVEMENT_THRES = 0.03
ROTATION_THRES = 20

NEAR_THRESHOLD = 0.5
NEAR_FAR_THRESHOLD = 4
NEAR_SIGMOID_VAL_AT_FAR = 0.9
NEAR_SIGMOID_SCALE = -np.log(1 / NEAR_SIGMOID_VAL_AT_FAR - 1) / (
    NEAR_FAR_THRESHOLD - NEAR_THRESHOLD
)

TOUCH_NEAR_THRESHOLD = 2.0
TOUCH_FAR_THRESHOLD = 4.0
TOUCH_SIGMOID_VAL_AT_FAR = 0.9
TOUCH_SIGMOID_SCALE = -np.log(1 / TOUCH_SIGMOID_VAL_AT_FAR - 1) / (
    TOUCH_FAR_THRESHOLD - TOUCH_NEAR_THRESHOLD
)

VISIBLE_DISTANCE = 1.25
VISIBLE_FAR_THRESHOLD = 4.0
VISIBLE_SIGMOID_VAL_AT_FAR = 0.9
VISIBLE_SIGMOID_SCALE = -np.log(1 / VISIBLE_SIGMOID_VAL_AT_FAR - 1) / (
    VISIBLE_FAR_THRESHOLD - VISIBLE_DISTANCE
)

SPATIAL_FAR = 1.0
SPATIAL_SIGMOID_VAL_AT_FAR = 0.9
SPATIAL_SIGMOID_SCALE = (
    -np.log(1 / SPATIAL_SIGMOID_VAL_AT_FAR - 1) / SPATIAL_FAR
)
